version: '3'

services:
  backend:
    build: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "${PORT}:${PORT}" # Adjust as needed
    networks:
      - mynet

  frontend:
    build: ./MyRPG
    ports:
      - "4200:80" # Angular served by Nginx on port 80 in container
    networks:
      - mynet

networks:
  mynet:

